version: 0.1

phases:
  install:
    commands:
      - echo Installing Node Modules...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building React Web application
      - npm run build-react
  post_build:
    commands:
      - echo Performing Test
      - npm run mochatest
artifacts:
  files:
    - '**/*'